### ISSUE TITLE
Thanks but this is completely unnecessary

### ISSUE THREAD

**Issue by Pharaoh2k** [AyAPS/PS4RestoreFPKGdeletion#1]
Just use this script:
PS4_db_Rebuilder_EXT-0.2.zip

**Comment by AyAPS** [comment]
Thanks but your issue is completely unnecessary

DB_Rebuilder fix "disapearred games", not "disapeared 'Delete option' " on the games.

My tool is "Windows native" (no dependencies like Python installation), plus most of users struggle to launch Python scripts, for these people nothing is easier than launching an EXE.

Just check comments (thanking) from a lot of people on PSXHAX, GBATEMP, French communities where I'm from etc, 1k+ downloads ≠ completely unnecessary...

**Comment by Pharaoh2k** [comment]
Fair enough.
If it's not yet unnecessary, it's gonna be when the updated native ps4 app comes out within a few days. Again, thank you for your helpful contribution and apologise if my issue upset u in any way as the dev. It was meant for users, not for you, but still your point taken 😉
