### ISSUE TITLE
Can't download 1.1

### ISSUE THREAD

**Issue by HsHura99** [AyAPS/PS4RestoreFPKGdeletion#2]
When I try to download I get download error

**Comment by AyAPS** [comment]
Tip: When having a technical problem, always indicate as much details as possible that can lead to diagnose and solve your problem. That's not the case of this issue.

This said, I suppose your problem is your antivirus deleting the dowloaded file, considering it's a virus because some are made with the same compiling tool.

My tool is clean, it's a "false positive".

I suggest you to create an exception in your AV before downloading the file.

If your AV is Windows Defender, read this:
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

Otherwise search how to do it for your AV solution.

**Comment by HsHura99** [comment]
Thanks ! It worked ! Your tool saved me
